### ISSUE TITLE
Path

### ISSUE THREAD

**Issue by OlivierLej** [lavarthan/heroku-build-pack-chrome-driver#1]
Hello,

Keen to use this package as we've run into an issue with the official Heroku Chromedriver buildpack. 

I'd like to know how to set CHROMEDRIVER_PATH ?

I previously used /app/.chromedriver/bin/chromedriver

Thanks for your help!

All the best

**Comment by lavarthan** [comment]
set `GOOGLE_CHROME_BIN` as `/app/.apt/usr/bin/google-chrome` and in your code 

```
options = webdriver.ChromeOptions()
options.binary_location = os.environ.get("GOOGLE_CHROME_BIN")
```

no need to explicitly set the chromedriver path
